server:
  port: 7003
  servlet:
    context-path: /logView
spring:
    thymeleaf:
      cache: false
## 自己的日志
#logging:
#  file: test.log
#  path: logs

logView:
  username: admin
  password: admin123