server:
  port: 7003
  servlet:
    context-path: /logView
spring:
    thymeleaf:
      cache: false
## 自己的日志
#logging:
#  file: test.log
#  path: logs

logView:
  username: admin
  password: 123456
  remoteIp: 127.0.0.1
  remoteUserName: 111
  remotePassWord: 222